"""add_backtest_reproducibility_columns

Revision ID: 199ad3600f8d
Revises: 341fbf77cdc6
Create Date: 2026-06-23 17:54:27.568559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199ad3600f8d'
down_revision: Union[str, Sequence[str], None] = '341fbf77cdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('commission_rate', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('slippage_bps', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('close_on_opposite_signal', sa.Boolean(), nullable=True))
    op.add_column('backtests', sa.Column('equity_curve', sa.JSON(), nullable=True))
    op.add_column('backtests', sa.Column('drawdown_curve', sa.JSON(), nullable=True))
    op.add_column('backtests', sa.Column('trades', sa.JSON(), nullable=True))
    op.add_column('backtests', sa.Column('ohlc_data', sa.JSON(), nullable=True))
    op.alter_column('backtests', 'position_size_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_backtests_user_id'), table_name='backtests')
    op.drop_column('backtests', 'user_id')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_column('strategies', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.add_column('backtests', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_backtests_user_id'), 'backtests', ['user_id'], unique=False)
    op.alter_column('backtests', 'position_size_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('backtests', 'ohlc_data')
    op.drop_column('backtests', 'trades')
    op.drop_column('backtests', 'drawdown_curve')
    op.drop_column('backtests', 'equity_curve')
    op.drop_column('backtests', 'close_on_opposite_signal')
    op.drop_column('backtests', 'slippage_bps')
    op.drop_column('backtests', 'commission_rate')
    # ### end Alembic commands ###
