"""Add user_id and backtest fields

Revision ID: 341fbf77cdc6
Revises: 40b60153d150
Create Date: 2026-06-23 11:14:34.849207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '341fbf77cdc6'
down_revision: Union[str, Sequence[str], None] = '40b60153d150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_next_backtests_created_at'), table_name='next_backtests')
    op.drop_index(op.f('idx_next_backtests_symbol'), table_name='next_backtests')
    op.drop_table('next_backtests')
    op.drop_index(op.f('idx_backtests_created_at'), table_name='backtests_new')
    op.drop_index(op.f('idx_backtests_symbol'), table_name='backtests_new')
    op.drop_table('backtests_new')
    op.add_column('backtests', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.add_column('backtests', sa.Column('position_size_type', sa.String(length=50), nullable=True))
    op.add_column('backtests', sa.Column('position_size', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('allow_short', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_backtests_user_id'), 'backtests', ['user_id'], unique=False)
    op.add_column('strategies', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_column('strategies', 'user_id')
    op.drop_index(op.f('ix_backtests_user_id'), table_name='backtests')
    op.drop_column('backtests', 'allow_short')
    op.drop_column('backtests', 'position_size')
    op.drop_column('backtests', 'position_size_type')
    op.drop_column('backtests', 'user_id')
    op.create_table('backtests_new',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('initial_capital', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('position_size', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('net_profit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_return', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('win_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('strategy_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('drawdown_curve', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trades', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('backtests_new_pkey'))
    )
    op.create_index(op.f('idx_backtests_symbol'), 'backtests_new', ['symbol'], unique=False)
    op.create_index(op.f('idx_backtests_created_at'), 'backtests_new', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('next_backtests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('initial_capital', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('position_size', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('net_profit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_return', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('win_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('strategy_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('drawdown_curve', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trades', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ohlc_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('next_backtests_pkey'))
    )
    op.create_index(op.f('idx_next_backtests_symbol'), 'next_backtests', ['symbol'], unique=False)
    op.create_index(op.f('idx_next_backtests_created_at'), 'next_backtests', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
