"""Add User model and kite auth fields

Revision ID: 3f37517690c8
Revises: 9df3f742bbf5
Create Date: 2026-07-29 14:32:31.847642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f37517690c8'
down_revision: Union[str, Sequence[str], None] = '9df3f742bbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('kite_access_token', sa.String(), nullable=True),
    sa.Column('kite_public_token', sa.String(), nullable=True),
    sa.Column('kite_login_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('backtests', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'backtests', 'users', ['user_id'], ['id'])
    op.add_column('strategies', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'strategies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'user_id')
    op.drop_constraint(None, 'backtests', type_='foreignkey')
    op.drop_column('backtests', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
