"""Add name tag description to strategies

Revision ID: 44a2deafe705
Revises: 3f37517690c8
Create Date: 2026-08-05 19:15:57.835308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a2deafe705'
down_revision: Union[str, Sequence[str], None] = '3f37517690c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('strategies', sa.Column('tag', sa.String(length=50), nullable=True))
    op.add_column('strategies', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'description')
    op.drop_column('strategies', 'tag')
    op.drop_column('strategies', 'name')
    # ### end Alembic commands ###
