"""Add exchange, position_side, execution_context

Revision ID: 9df3f742bbf5
Revises: a81342d5551e
Create Date: 2026-07-05 22:30:00.393183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df3f742bbf5'
down_revision: Union[str, Sequence[str], None] = 'a81342d5551e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('exchange', sa.String(length=50), nullable=True))
    op.add_column('backtests', sa.Column('position_side', sa.String(length=20), nullable=True))
    op.add_column('strategies', sa.Column('execution_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'execution_context')
    op.drop_column('backtests', 'position_side')
    op.drop_column('backtests', 'exchange')
    # ### end Alembic commands ###
