"""Add futures fields to backtest

Revision ID: a81342d5551e
Revises: 199ad3600f8d
Create Date: 2026-07-05 22:15:59.467628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81342d5551e'
down_revision: Union[str, Sequence[str], None] = '199ad3600f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('market_type', sa.String(length=50), nullable=False, server_default='equity'))
    op.add_column('backtests', sa.Column('multiplier', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('margin', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('expiry', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'expiry')
    op.drop_column('backtests', 'margin')
    op.drop_column('backtests', 'multiplier')
    op.drop_column('backtests', 'market_type')
    # ### end Alembic commands ###
