"""remove legacy kite columns

Revision ID: effa28c4341d
Revises: a38ea5ee4ede
Create Date: 2026-09-03 00:18:14.377991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'effa28c4341d'
down_revision: Union[str, Sequence[str], None] = 'a38ea5ee4ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_fills_fill_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_session_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_timestamp'), table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_index(op.f('ix_paper_orders_order_intent_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_session_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_table('paper_session_checkpoints')
    op.drop_table('alembic_version_backtest')
    op.drop_index(op.f('ix_paper_equity_snapshots_session_id'), table_name='paper_equity_snapshots')
    op.drop_table('paper_equity_snapshots')
    op.drop_index(op.f('ix_paper_positions_session_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_paper_sessions_session_id'), table_name='paper_sessions')
    op.drop_table('paper_sessions')
    op.drop_column('backtests', 'broker_name')
    op.drop_column('users', 'kite_login_time')
    op.drop_column('users', 'kite_public_token')
    op.drop_column('users', 'broker_credentials')
    op.drop_column('users', 'kite_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kite_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('broker_credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('kite_public_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('kite_login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('backtests', sa.Column('broker_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('paper_fills',
    sa.Column('fill_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_intent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filled_qty', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('filled_price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('fees', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('slippage', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_intent_id'], ['paper_orders.order_intent_id'], name=op.f('paper_fills_order_intent_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], name=op.f('paper_fills_session_id_fkey')),
    sa.PrimaryKeyConstraint('fill_id', name=op.f('paper_fills_pkey')),
    sa.UniqueConstraint('order_intent_id', name=op.f('paper_fills_order_intent_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_paper_fills_timestamp'), 'paper_fills', ['timestamp'], unique=False)
    op.create_index(op.f('ix_paper_fills_session_id'), 'paper_fills', ['session_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_fill_id'), 'paper_fills', ['fill_id'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('avg_entry_price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], name=op.f('paper_positions_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paper_positions_pkey')),
    sa.UniqueConstraint('session_id', 'symbol', name=op.f('uq_paper_position_session_symbol'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_paper_positions_session_id'), 'paper_positions', ['session_id'], unique=False)
    op.create_table('paper_equity_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('cash', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('unrealized_pnl', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('realized_pnl', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('total_equity', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], name=op.f('paper_equity_snapshots_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paper_equity_snapshots_pkey'))
    )
    op.create_index(op.f('ix_paper_equity_snapshots_session_id'), 'paper_equity_snapshots', ['session_id'], unique=False)
    op.create_table('alembic_version_backtest',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_backtest_pkc'))
    )
    op.create_table('paper_sessions',
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbols', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('strategy_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('session_id', name=op.f('paper_sessions_pkey'))
    )
    op.create_index(op.f('ix_paper_sessions_session_id'), 'paper_sessions', ['session_id'], unique=False)
    op.create_table('paper_session_checkpoints',
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instrument_token', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_processed_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], name=op.f('paper_session_checkpoints_session_id_fkey')),
    sa.PrimaryKeyConstraint('session_id', 'instrument_token', name=op.f('paper_session_checkpoints_pkey'))
    )
    op.create_table('paper_orders',
    sa.Column('order_intent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('limit_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('stop_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], name=op.f('paper_orders_session_id_fkey')),
    sa.PrimaryKeyConstraint('order_intent_id', name=op.f('paper_orders_pkey'))
    )
    op.create_index(op.f('ix_paper_orders_session_id'), 'paper_orders', ['session_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_order_intent_id'), 'paper_orders', ['order_intent_id'], unique=False)
    # ### end Alembic commands ###
