"""init_paper_trading

Revision ID: 79aa3221c54d
Revises: 
Create Date: 2026-08-11 15:47:04.682749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79aa3221c54d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('strategy_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_paper_sessions_session_id'), 'paper_sessions', ['session_id'], unique=False)
    op.create_table('paper_equity_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.Numeric(), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(), nullable=False),
    sa.Column('total_equity', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_equity_snapshots_session_id'), 'paper_equity_snapshots', ['session_id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('order_intent_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('limit_price', sa.Numeric(), nullable=True),
    sa.Column('stop_price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('order_intent_id')
    )
    op.create_index(op.f('ix_paper_orders_order_intent_id'), 'paper_orders', ['order_intent_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_session_id'), 'paper_orders', ['session_id'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'symbol', name='uq_paper_position_session_symbol')
    )
    op.create_index(op.f('ix_paper_positions_session_id'), 'paper_positions', ['session_id'], unique=False)
    op.create_table('paper_session_checkpoints',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('instrument_token', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('last_processed_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_id', 'instrument_token')
    )
    op.create_table('paper_fills',
    sa.Column('fill_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('order_intent_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('filled_qty', sa.Numeric(), nullable=False),
    sa.Column('filled_price', sa.Numeric(), nullable=False),
    sa.Column('fees', sa.Numeric(), nullable=False),
    sa.Column('slippage', sa.Numeric(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_intent_id'], ['paper_orders.order_intent_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['paper_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('fill_id'),
    sa.UniqueConstraint('order_intent_id')
    )
    op.create_index(op.f('ix_paper_fills_fill_id'), 'paper_fills', ['fill_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_session_id'), 'paper_fills', ['session_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_timestamp'), 'paper_fills', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_fills_timestamp'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_session_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_fill_id'), table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_table('paper_session_checkpoints')
    op.drop_index(op.f('ix_paper_positions_session_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_paper_orders_session_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_order_intent_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_paper_equity_snapshots_session_id'), table_name='paper_equity_snapshots')
    op.drop_table('paper_equity_snapshots')
    op.drop_index(op.f('ix_paper_sessions_session_id'), table_name='paper_sessions')
    op.drop_table('paper_sessions')
    # ### end Alembic commands ###
